apiVersion: install.armadaproject.io/v1alpha1
kind: Server
metadata:
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: server-sample
    app.kubernetes.io/part-of: armada-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: armada-operator
  name: server-sample
spec:
  # TODO(user): Add fields here
